[tox]
minversion = 3.0
envlist = molecule
skipsdist = true

[testenv]
allowlist_externals =
    molecule
    ansible-galaxy
    bash
    git
    docker
    podman
passenv =
    HOME
    TERM
    PATH
    DOCKER_HOST
    DOCKER_TLS_VERIFY
    DOCKER_CERT_PATH
    XDG_RUNTIME_DIR
commands =
    python3.9 -m molecule test -s podman
